# Generated by Django 3.2 on 2022-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rasterfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_workspace', models.CharField(max_length=100)),
                ('file_archive', models.FileField(upload_to='tmp/')),
            ],
        ),
    ]
